version: '3.8'
services:
  mongo:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 5550:27017
    volumes:
      - ./.docker-data/mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 10s

  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "127.0.0.1:4566:4566"            
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bootstrap/localstack:/etc/localstack/init/ready.d

  sendgrid-mock:
    image: ghashange/sendgrid-mock:1.9.0
    platform: linux/amd64
    ports:
      - 4500:3000
    environment:
      - API_KEY=SG.api-key
