export enum NotificationType {
  NOTIFY_WINNING_BIDDER = 'NOTIFY_WINNING_BIDDER',
  NOTIFY_BIDDER_ABOUT_PAYMENT = 'NOTIFY_BIDDER_ABOUT_PAYMENT',
  AUCTION_RESULT_TO_BIDDER = 'AUCTION_RESULT_TO_BIDDER',
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}
