name: Pull Request

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Containers
      run: docker-compose up -d

    - name: Install Node v20.9.0
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0

    - name: Install Dependencies
      run: npm ci
    
    - name: Build app
      run: npm run build

    - name: Lint
      run: npm run lint
    
    - name: Run Unit Tests
      run: npm run test:unit

    - name: Run Integration Tests
      run: npm run test:integration
